# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefinedcategory',
            name='rank',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
